pipeline {
    agent any
    stages {
        stage ('Clean Up'){
            steps {
                deleteDir()
            }
        }
        stage ('Stage 1'){
            steps {
                echo "Hi! from stage 1"
            }
        }
       stage ('Stage 2'){
            steps {
                echo "Hi! from stage 2"
            }
        }
        stage ('Stage 3'){
            steps {
                echo "Hi! from stage 3"
            }
        }
        stage ('Stage 4'){
            steps {
                echo "Hi! from stage 4"
            }
        }
        stage ('Stage 5'){
            steps {
                echo "Hi! from stage 5"
            }
        }
    }
}
