pipeline {
    agent any

    parameters {
        choice( choices:["Test", "Dev", "QA", "Pre-Prod", "Prod"], description: "Which environment to deploy in?", name:"deployEnv") 
    }

    stages {
        stage("Demo"){
            steps {
                echo "Choice is set to: ${params.deployEnv}"
            }
        }
    }
}
