pipeline {
    agent any

    environment {
        def myString = "Hello World"
        def myNumber = 8
        def myBool = true
    }

    stages {
        stage("Demo"){
            steps {
                echo "myString: ${myString}"
            }
        }
    }
}
