pipeline {
    agent any

    parameters {
        string(defaultValue: "", description: "Deployment Name", name:"deployName")
        choice( choices:["EU-WEST-2A", "EU-WEST-2B", "EU-WEST-2C"], description: "Select the AZ", name:"azDeploy") 
        booleanParam(defaultValue: false, description: "Confirm Deployment?", name: "confirmDeploy")
    }

    stages {
        stage("Deploy"){
            steps {
                echo "String is set to: ${params.custDeploy} \n"
                echo "Choice is set to: ${params.AZDeploy} \n"
                echo "Boolean is set to: ${params.deployConfirm} \n"
            }
        }
    }
}
