pipeline {
    agent any
    stages {
        stage ('Clean Up'){
            steps {
                deleteDir()
            }
        }
        stage ('Clone Repo'){
            steps {
                sh 'git clone https://github.com/jenkins-docs/simple-java-maven-app.git'
            }
        }
        stage ('Build'){
            steps {
                dir{'simple-java-maven-app'} {
                    sh "sed -i 's/3.8.6/3.6.3/g' pom.xml"
                    sh 'mvn clean install'
                }
            }
        }
        stage ('Test'){
            steps {
                dir{'simple-java-maven-app'} {
                    sh 'mvn test'
                }
            }
        }
    }
}
